### Todo 등록
POST {{apiUrl}}/todos
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
    "category": "algorithm",
    "title": "boj 1422",
    "mon": 1,
    "tue": 1,
    "wed": 1,
    "thu": 1,
    "fri": 1,
    "sat": 1,
    "sun": 1
}

### Todo 전체 조회
GET {{apiUrl}}/todos?day=
Authorization: {{authorizationToken}}

### Todo 상세 조회
GET {{apiUrl}}/todos/3
Authorization: {{authorizationToken}}

### Todo 수정
PUT {{apiUrl}}/todos/4
Authorization: {{authorizationToken}}
Content-Type: application/json;charset=UTF-8

{
  "category": "programmers",
  "title": "kakao2021-1",
  "mon": 0,
  "tue": 0,
  "wed": 1,
  "thu": 1,
  "fri": 1,
  "sat": 0,
  "sun": 0
}

### Todo 삭제
DELETE {{apiUrl}}/todos/1
Authorization: {{authorizationToken}}