### 구글 로그인
### http://{{IP address}}/api/oauth2/authorize/google?redirect_uri=chrome-extension://epiifnjgnimepgnkbeeljnkajpehbeln/index.html


### User 정보 조회
GET {{apiUrl}}/users
Authorization: {{authorizationToken}}

### 유저 로그인
POST {{apiUrl}}/users/login
Content-Type: application/json;charset=UTF-8

{
  "email": "haru@gmail.com"
}

> {%
client.global.set("authorizationToken", "Bearer " + response.body.accessToken);
client.log("Auth Token : " + client.global.get("authorizationToken"));
%}

### 유저 로그아웃
GET {{apiUrl}}/users/logout
Authorization: {{authorizationToken}}